channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base
  - r-ape
  - r-tidyverse
  - r-gtable
  - r-gridgraphics
  - bioconductor-genbankr
  - r-rcolorbrewer
  - r-ggnewscale
  - r-gggenes
  - r-phytools
  - bioconductor-ggtree
  - glib
